version: 0.1.2
maquina: 
    numero_maquina: 6
    numero_maquina_bbdd: '8'
    #maquina_escaneo -> 2: maquina8
    #                -> 11: maquina7
    #                -> 8: maquina6
    #                -> 5: maquina1 (reserva)
    puesta_pro: "Septiembre24"
    ubicacion: "Cordoba"
    puesto: "sala escaneo, central"
    novedades_maquina: "Freno resina, ruedas inf 2aET resina, ruedas inf camara resina, chapas laterales de fijacion de distancias,  amortiguacion con abrazaderas de laton"
    freno: "estrecho/64.5/versionNoviembre/2paredes/sinTopBottom"
    bandeja: "nueva/acero_carbono"
    caja_electronica: "2a version armario"
    sensor_dobles: "pepperl fluchs"
    sensor_disparo_maquina: "pepperl fluchs potenciometro"
    sensor_encoder: "omron"
    acople_volteador: "nuevo_acople_flexible_mejorado_tpu"
    pc: "pcv3.0"
    camara: "mars4096-l28/gris"
    perfil_camara : "+22.5mm"
    fuente_iluminaria: "nueva/conector 4pines"
    driver: "dm542t/ stepperonline"
    motores: "nema17/24 stepper online"
    ultima_revision: "06.09.2024: etiqueta inteligente / 27.03.2025 cambiamos optos por los correctos 24 -> 5v"
    version_sw: "07022025.1"
    complementos_sw: '{"fin_paquete_desordenado.png":"/logo/fin_paquete_desordenado.png","fin_paquete_sin_codigos.png":"/logo/fin_paquete_sin_codigos.png"}'
    # 22102024.3
    rodillo_inferior_2etapa: "resina flex"
    rodillos_inferior_camara: "resina flex"    
    
funcionamiento:
    modo_interfaz_exe: "Produccion"
    #Test
    #Produccion
    #Ambos
camera:
    model_camera: "mars4096-l28"
    trigger_camera: "22000"
    f_camera: "23000"
    roi_camera_h: "2850"
    reverse_x_camera: "1"
    #comunes ambas camaras
    roi_camera_w: "4096"
    t_exposicion_camera: "33"
    t_timeout_camera: "3000"
    # tipo_flanco: "RisingEdge"
    tipo_flanco: "FallingEdge"


    # roi_cabecera_ymin: "333"
    # roi_cabecera_ymax: "1002"
    # roi_cabecera_xmin: "800"
    # roi_cabecera_xmax: "2260"

    roi_cabecera_ymin: "50"
    roi_cabecera_ymax: "400"
    roi_cabecera_xmin: "700"
    roi_cabecera_xmax: "2000"

    roi_cod_dispensacion_ymin: "400"
    roi_cod_dispensacion_ymax: "900"
    roi_cod_dispensacion_xmin: "1700"
    roi_cod_dispensacion_xmax: "2500"
    

    desde_x: "100"
    hasta_x: "2750"
    desde_y: "400"
    hasta_y: "3935"

    # desde_x: "0"
    # hasta_x: "2850"
    # desde_y: "0"
    # hasta_y: "4096"

    t_line_debouncing: "1000000"

