version: 0.1.0
maquina: 
    numero_maquina: 2
    numero_maquina_bbdd: '11'
    #maquina_escaneo -> 2: maquina1
    #                -> 11: maquina2
    #                -> 5: maquina3
    #                -> 8: maquina4
    puesta_pro: "febrero24 // maq actualizada marzo25"
    ubicacion: "Cordoba"
    puesto: "maquina de repuesto" #"sala_escaneo/eladia"
    novedades_maquina: "firmware bandeja actualizado con la lectura minima de los sharp" #"está en mantenimiento completo"
    freno: "version sin paredes" #"estrecho/64.5"
    bandeja: "acero_inoxidable"
    caja_electronica: "nueva"
    sensor_dobles: "pepperl fuchs"
    sensor_disparo_maquina: "pepperl fuchs"
    sensor_encoder: "pepperl fuchs"
    acople_volteador: "nuevo separable"
    pc: "pcv2.0"
    camara: "mars4096-l26/naranja/3cables"
    perfil_camara: "+22.5"
    fuente_iluminaria: "nueva"
    
    driver: "dm542t/ stepperonlin" #"tb6600/ 2as Marcas"
    motores: "nema17/24 stepper online" #"amazon/2as Marcas"
    ultima_revision: "26/04/2025" #"12.09.2024: actualizaciones ota / sync config"
    version_sw: "04122024.1"
    # version_sw: "07022025.1"
    complementos_sw: '{"fin_paquete_desordenado.png":"/logo/fin_paquete_desordenado.png","fin_paquete_sin_codigos.png":"/logo/fin_paquete_sin_codigos.png"}'  
    rodillo_inferior_2etapa: "tpu 95a con paredes"
    rodillos_inferior_camara: "tpu 95a con paredes"

funcionamiento:
    modo_interfaz_exe: "Produccionn"
    #Test
    #Produccion
    #Ambos
camera:
    model_camera: "mars4096-l26"
    trigger_camera: "27000"
    f_camera: "24500"
    roi_camera_h: "2900"
    reverse_x_camera: "0"
    #comunes ambas camaras
    roi_camera_w: "4096"
    t_exposicion_camera: "33"
    t_timeout_camera: "3000"
    tipo_flanco: "RisingEdge"
    # tipo_flanco: "FallingEdge"


    roi_cabecera_ymin: "50"
    roi_cabecera_ymax: "550"
    roi_cabecera_xmin: "550"
    roi_cabecera_xmax: "2300"

    roi_cod_dispensacion_ymin: "400"
    roi_cod_dispensacion_ymax: "900"
    roi_cod_dispensacion_xmin: "1700"
    roi_cod_dispensacion_xmax: "2500"

    desde_x: "0"
    hasta_x: "2850"
    desde_y: "220"
    hasta_y: "3890"

    t_line_debouncing: "1000000"
