version: 0.1.0
maquina: 
    numero_maquina: 1
    numero_maquina_bbdd: '2'
    #maquina_escaneo -> 2: maquina1
    #                -> 11: maquina2
    #                -> 5: maquina3
    #                -> 8: maquina4
    puesta_pro: "febrero24"
    ubicacion: "Cordoba"
    puesto: "sala_escaneo/felipe"
    novedades_maquina: "prototipo1 felipe: estructura mas larga / driver y pp antiguos "
    freno: "ancho/67.5"
    bandeja: "antigua"
    caja_electronica: "antigua"
    sensor_dobles: "pepperl fluchs"
    sensor_disparo_maquina: "xub4ananl2"
    sensor_encoder: "xub4ananl2"
    acople_volteador: "antiguo"
    pc: "pcv1.0"
    camara: "mars4096-l28/naranja/antigua"
    perfil_camara: "0mm"
    fuente_iluminaria: "nueva/conector 4pines"
    motor_retorno: "motorac/variador"
    driver: "tb6600/ 2as Marcas"
    motores: "amazon/2as Marcas"
    ultima_revision: "12.09.2024: actualizaciones ota / sync config"
    version_sw: "02122024.2"
    # version_sw: "12092024.4"

funcionamiento:
    modo_interfaz_exe: "Produccionn"
    #Test
    #Produccion
    #Ambos
camera:
    model_camera: "mars4096-l28"
    trigger_camera: "33500"
    f_camera: "20500"
    roi_camera_h: "2750"
    reverse_x_camera: "1"
    #comunes ambas camaras
    roi_camera_w: "4096"
    t_exposicion_camera: "33"
    t_timeout_camera: "3000"
    tipo_flanco: "RisingEdge"
    # tipo_flanco: "FallingEdge"


    # roi_cabecera_ymin: "20"
    # roi_cabecera_ymax: "520"
    # roi_cabecera_xmin: "600"
    # roi_cabecera_xmax: "2030"

    roi_cabecera_ymin: "50"
    roi_cabecera_ymax: "400"
    roi_cabecera_xmin: "700"
    roi_cabecera_xmax: "2000"

    roi_cod_dispensacion_ymin: "400"
    roi_cod_dispensacion_ymax: "900"
    roi_cod_dispensacion_xmin: "1700"
    roi_cod_dispensacion_xmax: "2500"
    
    desde_x: "0"
    hasta_x: "2725"
    desde_y: "150"
    hasta_y: "4050"

    t_line_debouncing: "1000000"
