version: 0.1.0
maquina: 
    numero_maquina: 4
    numero_maquina_bbdd: '8'
    #maquina_escaneo -> 2: maquina1
    #                -> 11: maquina2
    #                -> 5: maquina3
    #                -> 8: maquina4
    id_anydesk: '1398299185'
    puesta_pro: "Julio24"
    ubicacion: "Malaga"
    puesto: "puesto central"
    novedades_maquina: ""
    freno: "estrecho/64.5"
    bandeja: "nueva/acero_inox"
    caja_electronica: "2a version armario  // opto 1 canal 4 quemado ?¿ Diciembre24 --> opto2"
    sensor_dobles: "pepperl fluchs"
    sensor_disparo_maquina: "xub4ananl2"
    sensor_encoder: "omron"
    acople_volteador: "antiguo_gordo_pla"
    pc: "pcv3.0"
    camara: "mars4096-l28/naranja"
    perfil_camara : "22.5mm"
    fuente_iluminaria: "nueva/conector 4pines"
    valor_iluminaria: '208'
    arduino_main: "china"
    arduino_bandeja: "china"
    arduino_auxiliar: "china"    
    driver: "dm542t/ stepperonline"
    motores: "nema17/24 stepper online"
    ultima_revision: "12.09.2024: actualizaciones ota / sync config || 19.02.2025: bandeja inoxidable nueva, nuevo sistema acoples 1ª y 2ªET, eje inferior 2aET nuevo"
    #version_sw: "04122024.1"
    version_sw: "07022025.1"
    complementos_sw: '{"fin_paquete_desordenado.png":"/logo/fin_paquete_desordenado.png","fin_paquete_sin_codigos.png":"/logo/fin_paquete_sin_codigos.png"}'   
    rodillo_inferior_2etapa: "tpu 82a naranja sin paredes"
    rodillos_inferior_camara: "tpu 82a naranja sin paredes"    
    # version_sw: "16092024.2"

funcionamiento:
    modo_interfaz_exe: "Produccionn"
    #Test
    #Produccion
    #Ambos
camera:
    model_camera: "mars4096-l28"
    trigger_camera: "20000"
    f_camera: "21500"
    roi_camera_h: "2650"
    reverse_x_camera: "1"
    #comunes ambas camaras
    roi_camera_w: "4096"
    t_exposicion_camera: "33"
    t_timeout_camera: "3000"
    tipo_flanco: "RisingEdge"
    # tipo_flanco: "FallingEdge"

    roi_cabecera_ymin: "50"
    roi_cabecera_ymax: "400"
    roi_cabecera_xmin: "700"
    roi_cabecera_xmax: "2000"

    roi_cod_dispensacion_ymin: "400"
    roi_cod_dispensacion_ymax: "900"
    roi_cod_dispensacion_xmin: "1700"
    roi_cod_dispensacion_xmax: "2500"
    
    # roi_cabecera_ymin: "1"
    # roi_cabecera_ymax: "550"
    # roi_cabecera_xmin: "400"
    # roi_cabecera_xmax: "2250"


    desde_x: "50"
    hasta_x: "2600"
    #desde_y: "340"
    desde_y: "250"
    hasta_y: "3780"

    t_line_debouncing: "1000000"
