version: 0.1.0
maquina: 
    numero_maquina: 5
    numero_maquina_bbdd: '2'
    id_anydesk: "1493206796"
    #maquina_escaneo -> 2: maquina1
    #                -> 11: maquina2
    #                -> 5: maquina3
    #                -> 8: maquina4
    puesta_pro: "Julio24"
    ubicacion: "Málaga"
    puesto: "derecha pegado a columna"
    novedades_maquina: "rodillos salida camara de resina"
    freno: "estrecho/64.5, tpu"
    bandeja: "nueva/acero_carbono --> inox Febrero25"
    caja_electronica: "2a version armario"
    sensor_dobles: "pepperl fluchs"
    sensor_disparo_maquina: "pepperl fluchs potenciometro"
    sensor_encoder: "omron"
    acople_volteador: "nuevo_acople_flexible_mejorado_tpu"
    pc: "pcv3.0"
    camara: "mars4096-l28/gris"
    perfil_camara : "0mm --> 22.5mm Febrero25"
    fuente_iluminaria: "nueva/conector 4pines"
    valor_iluminaria: '198'
    arduino_main: "china"
    arduino_bandeja: "china"
    arduino_auxiliar: "china"    
    driver: "dm542t/ stepperonline"
    motores: "nema17/24 stepper online"
    ultima_revision: "12.09.2024: actualizaciones ota / sync config // 19.02.2025: nuevo sistema acoples 1ª y 2ª etapas. 2aET inferior cambiada. Cambio de bandeja"
    #version_sw: "04122024.1"
    # version_sw: "20012025.2"
    version_sw: "07022025.1"
    complementos_sw: '{"fin_paquete_desordenado.png":"/logo/fin_paquete_desordenado.png","fin_paquete_sin_codigos.png":"/logo/fin_paquete_sin_codigos.png"}'   
    rodillo_inferior_2etapa: "tpu 95a con paredes"
    rodillos_inferior_camara: "resina flex"        
    # version_sw: "16092024.2"

funcionamiento:
    modo_interfaz_exe: "Produccion"
    #Test
    #Produccion
    #Ambos
camera:
    model_camera: "mars4096-l28"
    trigger_camera: "25000"
    f_camera: "23000"
    roi_camera_h: "2650"
    reverse_x_camera: "1"
    #comunes ambas camaras
    roi_camera_w: "4096"
    t_exposicion_camera: "33"
    t_timeout_camera: "3000"
    # tipo_flanco: "RisingEdge"
    tipo_flanco: "FallingEdge"

    roi_cabecera_ymin: "50"
    roi_cabecera_ymax: "400"
    roi_cabecera_xmin: "700"
    roi_cabecera_xmax: "2000"

    roi_cod_dispensacion_ymin: "400"
    roi_cod_dispensacion_ymax: "900"
    roi_cod_dispensacion_xmin: "1700"
    roi_cod_dispensacion_xmax: "2500"
    
    # roi_cabecera_ymin: "20"
    # roi_cabecera_ymax: "420"
    # roi_cabecera_xmin: "600"
    # roi_cabecera_xmax: "2030"

    desde_x: "0"
    hasta_x: "2650"
    desde_y: "250"
    hasta_y: "3820"

    t_line_debouncing: "1000000"
