version: 0.1.0
maquina: 
    numero_maquina: 3
    numero_maquina_bbdd: '5'
    id_anydesk: "1712320823"
    #maquina_escaneo -> 2: maquina1
    #                -> 11: maquina2
    #                -> 5: maquina3
    #                -> 8: maquina4
    puesta_pro: "Agosto24"
    ubicacion: "Malaga"
    puesto: "esquina ventana"
    novedades_maquina: "caja de electronica v1 nueva mas pequeña"
    freno: "estrecho/64.5"
    bandeja: "antigua"
    caja_electronica: "1a version armario"
    sensor_dobles: "pepperl fluchs"
    sensor_disparo_maquina: "xub4ananl2"
    sensor_encoder: "negro ajustable"
    acople_volteador: "antiguo_gordo_completo"
    pc: "pcv3.0"
    camara: "mars4096-l28/naranja"
    perfil_camara : "0mm"
    fuente_iluminaria: "nueva/conector 4pines"
    valor_iluminaria: '208'
    arduino_main: "elegoo"
    arduino_bandeja: "elegoo"
    arduino_auxiliar: "elegoo"
    driver: "dm542t/ stepperonline"
    motores: "nema17/24 stepper online"
    ultima_revision: "12.09.2024: actualizaciones ota / sync config"
    #version_sw: "04122024.1"
    version_sw: "20012025.2"
    complementos_sw: '{"fin_paquete_desordenado.png":"/logo/fin_paquete_desordenado.png","fin_paquete_sin_codigos.png":"/logo/fin_paquete_sin_codigos.png"}'    
    #"12092024.2"

funcionamiento:
    modo_interfaz_exe: "Produccionn"
    #Test
    #Produccion
    #Ambos
camera:
    model_camera: "mars4096-l28"
    trigger_camera: "24700"
    f_camera: "22500"
    roi_camera_h: "2700"
    reverse_x_camera: "1"
    #comunes ambas camaras
    roi_camera_w: "4096"
    t_exposicion_camera: "33"
    t_timeout_camera: "3000"
    tipo_flanco: "RisingEdge"


    # roi_cabecera_ymin: "20"
    # roi_cabecera_ymax: "560"
    # roi_cabecera_xmin: "400"
    # roi_cabecera_xmax: "2400"

    roi_cabecera_ymin: "50"
    roi_cabecera_ymax: "550"
    roi_cabecera_xmin: "700"
    roi_cabecera_xmax: "2000"

    roi_cod_dispensacion_ymin: "400"
    roi_cod_dispensacion_ymax: "950"
    roi_cod_dispensacion_xmin: "1700"
    roi_cod_dispensacion_xmax: "2500"

    desde_x: "0"
    hasta_x: "2650"
    desde_y: "200"
    hasta_y: "3896"

    t_line_debouncing: "1000000"
