version: 0.1.0
maquina: 
    numero_maquina: 2
    numero_maquina_bbdd: '11'
    #maquina_escaneo -> 2: maquina1
    #                -> 11: maquina2
    #                -> 5: maquina3
    #                -> 8: maquina4
    puesta_pro: "febrero24"
    ubicacion: "Cordoba"
    puesto: "sala_escaneo/eladia"
    novedades_maquina: "prototipo2 eladia: / driver y pp antiguos "
    freno: "estrecho/64.5"
    bandeja: "nueva/acero_carbono"
    caja_electronica: "antigua"
    sensor_dobles: "chino"
    sensor_disparo_maquina: "xub4ananl2"
    acople_volteador: "antiguo"
    pc: "pcv2.0"
    ultima_revision: "12.09.2024: actualizaciones ota / sync config"
    version_sw: "12092024.4"

funcionamiento:
    modo_interfaz_exe: "Produccionn"
    #Test
    #Produccion
    #Ambos
camera:
    model_camera: "mars4096-l26"
    trigger_camera: "27000"
    f_camera: "24500"
    roi_camera_h: "2900"
    reverse_x_camera: "0"
    #comunes ambas camaras
    roi_camera_w: "4096"
    t_exposicion_camera: "33"
    t_timeout_camera: "3000"
    tipo_flanco: "RisingEdge"
    # tipo_flanco: "FallingEdge"


    roi_cabecera_ymin: "50"
    roi_cabecera_ymax: "550"
    roi_cabecera_xmin: "550"
    roi_cabecera_xmax: "2300"

    desde_x: "0"
    hasta_x: "2850"
    desde_y: "220"
    hasta_y: "3890"

    t_line_debouncing: "1000000"
